skinparam dpi 150

skinparam default {
    FontColor #444455
	FontSize 12
	BorderColor #333344
}

skinparam title {
    FontColor #444455
	FontStyle bold
	FontSize 28
}
skinparam package {
	BorderColor #111122
}
skinparam sequence {
    ParticipantPadding 20
    BoxPadding 10
    MessageAlign center
    ArrowColor #BFD700
    ActorBackgroundColor #7971C0
    ActorBorderColor #5956AC
    LifeLineBackgroundColor #DDDDDD
    LifeLineBorderColor #CCCCCC
    ParticipantFontColor #FFFFFF
    ParticipantBackgroundColor #0087D5
    ParticipantBorderColor #005A87
    ParticipantFontStyle bold
    BoxBackgroundColor #D9E0FA
    BoxBorderColor #3e77a7
}
skinparam {
    DatabaseBackgroundColor #FBD64B
    DatabaseBorderColor #FFBC00
}
skinparam class {
    BackgroundColor white-#FBEA8C
    BackgroundColor<<Table>> white-AAD6E6
    BackgroundColor<<Entity>> white-AAD6E6
    BackgroundColor<<MappedSuperclass>> white-AAB5E6
	ArrowColor #333344
	BorderColor #333344
	FontStyle bold
}
skinparam component {
    BackgroundColor white-#FBEA8C
	ArrowColor #333344
	BorderColor #333344
	FontStyle bold
}
skinparam node {
    BackgroundColor white-#FBEA8C
	ArrowColor #333344
	BorderColor #333344
	FontStyle bold
}
skinparam partition {
	ArrowColor #333344
	BorderColor #333344
	FontStyle bold
}
skinparam activity {
    BackgroundColor white-#FBEA8C
	ArrowColor #333344
	BorderColor #333344
}
skinparam branch {
    BackgroundColor white-#FBEA8C
	ArrowColor #333344
	BorderColor #333344
}
skinparam state {
    BackgroundColor white-#FBEA8C
	ArrowColor #333344
	BorderColor #333344
}
skinparam note {
    BackgroundColor #FBE96C
	BorderColor #E0B646
}
skinparam state {
    BackgroundColor white-#FBEA8C
	ArrowColor #333344
	BorderColor #333344
	FontStyle bold
}
skinparam object {
    BackgroundColor white-#AAD6E6
	ArrowColor #333344
	BorderColor #333344
	FontStyle bold
}
skinparam legend {
    BackgroundColor white-#EEEEEE
	BorderColor #CCCCCC
}

hide footbox

!define Table(name,desc) class name as "desc" << (T,#AAD6E6) >> <<Table>>
!define Table(name) class name << (T,#AAD6E6) >> <<Table>>
!define Entity(name,desc) class name as "desc" << (T,#AAD6E6) >> <<Entity>>
!define Entity(name) class name << (T,#AAD6E6) >> <<Entity>>
!define MappedSuperclass(name) class name << (M,#AAB5E6) >> <<MappedSuperclass>>
!define MappedSuperclass(name,desc) class name as "desc" << (T,#AAB5E6) >> <<Entity>>
!define primary_key(x) <&key> <b><color:#286ACD>x</color></b>
!define foreign_key(x) <&share> <b><color:#0C7A79>x</color></b>
!define id(x) <b>x</b>
!define unique(x) <&tag> <b><u>x</u></b>
!define not_null(x) <&tag> <b>x</b>
!define column(x) <&chevron-right> <b>x</b>
!define readonly(x) <i>x</i>

!define synthetic(x) <&info> <color:#666666>x</color>
!define reference(x) <color:#5A6E9C><u>x</u></color>
