@startuml

!include ../../theme/styles.iuml

actor "User" as user
participant "Frontend Application" as frontend
participant "WAF/IAM" as waf
participant "Backend Application" as backend
database "Persistence" as db

user -> frontend: start
frontend -> waf: login
waf --> user: show login form \n(prompt for credentials)
user -> waf: login (credentials)
waf --> frontend: logged in (session or bearer token)

frontend -> waf: request (session or bearer token)
activate frontend
waf -> backend: forward request (JWT)
activate backend
backend --> backend: extract login user + roles from JWT
backend -> db: query data
backend --> frontend: response
deactivate backend
deactivate frontend

@enduml
